# Generated by Django 3.1.3 on 2020-12-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bno', models.IntegerField()),
                ('bname', models.CharField(max_length=100)),
                ('bauthor', models.CharField(max_length=25)),
                ('byear', models.IntegerField()),
            ],
        ),
    ]
